sudo: required
language: elixir
elixir: '1.6'
otp_release: '20.0'
environment:
  - MIX_ENV=test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libc-ares-dev libssl-dev uuid-dev
  - wget http://mosquitto.org/files/source/mosquitto-1.4.tar.gz
install:
  - tar xvzf mosquitto-1.4.tar.gz
  - cd mosquitto-1.4
  - make
  - sudo make install
  - cd ..
  - sudo cp -R ./mosquitto/certs/ /etc/mosquitto/certs/
  - sudo cp ./mosquitto/mosquitto.conf /etc/mosquitto/mosquitto.conf
before_script:
  - mosquitto -d -c /etc/mosquitto/mosquitto.conf
  - mix local.hex --force
  - mix local.rebar
  - MIX_ENV=test mix deps.get
script:
  - sleep 10
  - MIX_ENV=test mix test
